### ISSUE TITLE
Pregled rada

### ISSUE THREAD

**Issue by mrdakj** [MATF-RG17/RG001-kocka-kocka-kockica#1]
Napomena: Kursor je sakriven.

Zamolila bih Vas da pogledate klase.

**Comment by ivan-cukic-matf** [comment]
Generalne zamerke (nevezano za broj poena, vezano vecinom za to da C++ nije C):

- NULL se u C++-u zove nullptr
- `this->` nije potreban osim ako imate shadowing članske promenljive lokalnom (i u nekim drugim veoma specifičnim situacijama)
- koristite std::string umesto char* - Material treba da cisti za sobom, ne treba korisnik (Model) neke strukture/klase da zna koja polja treba da se ociste koja ne. Kad god poželite u C++-u da pozovete `free`, zapitajte se zašto
- fopen i slicni -> std::istream
- `unused_function_arg` je predugacko ime za ovaj makro. Pogotovo sto isti radi i za ostale `unused` stvari
- mouse.cpp:206 treba dokumentovati - nije ocigledno zbog cega je bitna sirina i visina prozora dok se ne pogleda get_id funkcija.
- Kad koristite enume, vrednosti unutar enuma 'prljaju' globalni prostor imena. Istrazite `enum class`, ili imenujte vrednosti enuma malo detaljnjije - umesto `Up`, `UpDirection` i slicno jer postoji mogucnost da ce jos negde biti potreban `Up`.
- Argumenti konstruktora (i ostalih f-je) mogu da imaju podrazumevane vrednosti `Color(float r=1, float g=0, ...)`
- Nemojte da mesate CamelCase i snake_case ako ne morate. U C++-u je to malo problematicno - svaka biblioteka ima svoj stil, ali kad pisete svoj kod, odlucite se za jedno ili drugo, ili odlucite kad koristite jedno, a kad drugo ako zelite da mesate.
- `dfs() == dfs(car)`?
- Zasto `ut_Point` umesto `Point` ili `namespace Ut { class Point}`. Zasto je `Point` "utility", a `Vector3f` nije

Sto se tice organizacije, nemam neke zamerke. Ne vidim da biste mogli jednostavnije da organizujete kod.
